In [ ]:
import pandas as pd
df_production = pd.read_csv("../data/22_생산정보.csv", encoding="cp949")
df_growth = pd.read_csv("../data/22_생육정보.csv", encoding="cp949")
df_energy = pd.read_csv("../data/22_에너지사용정보.csv", encoding="cp949")
df_environment = pd.read_csv("../data/22_환경정보.csv", encoding="cp949",low_memory=False)

### 개념 정리
양액: 식물 재배에 필요한 질소, 인산, 칼륨 등 필수 양분을 물에 녹여 만든 액상 비료 또는 영양액
배지: 흙 대신 식물 뿌리를 잡아주는 재료
공급 EC: 식물에게 주기 직전 양액의 농도
배지 EC: 배지(코코피트 등) 안에 실제로 존재하는 염류 농도
        -> 시간이 지나면 배지 EC가 올라갈 수 있음
배액 EC: 식물 뿌리를 거쳐 나온 물의 농도
        -> 식물이 영양을 얼마나 먹었는지 알 수 있음
공급 pH: 식물에게 주는 양액의 산도
배액 pH: 뿌리를 지나 나온 물의 산도
토양 EC: 토양 속에 녹아 있는 염류(영양분)의 농도
온도1 / 온도2: 서로 다른 위치에서 측정한 실내 공기 온도 센서값
난방관1온도 / 난방관2온도: 난방 배관(파이프) 표면 온도
                -> 공기 온도가 아니라 난방 시스템 자체의 온도
난방설정온도: 목표온도
이슬점온도: 공기 중 수분이 응결되기 시작하는 온도
                -> 공기중 수증기량에 의존적인 데이터
예비온도: 보조 목표온도 
                -> 주 센서가 고장났을 때 쓰는 온도
3 way: 3방 밸브, 물이나 온수의 흐름 방향을 조절하는 밸브
                ->밸브 개도율(%), 흐름을 정밀 제어하기 위해
순환펌프: 온수를 배관 안에서 계속 돌려주는 펌프
훈증기: 연무(안개) 형태로 약제 살포(병해충 방제, 소독)
유동팬: 내부 공기 순환용 팬
배기팬: 외부로 공기를 빼내는 팬
보광: 보조 조명, 일조 부족 시 빛 보충

### 고민사항
이 농가는 배지 재배인가, 토양 재배인가?
-> 식물 생육에 직접 영향을 주는 것은 "뿌리가 위치한 환경"이기 때문

A. 배지 재배라면

뿌리 → 코코피트/락울 등 배지에 위치
배지EC, 배지수분이 핵심 변수
토양EC는 보조 모니터링 지표 가능성
-> 이 경우 NT가 핵심 데이터

B. 토양 재배라면

뿌리 → 흙에 직접 위치
토양EC, 토양PH가 핵심 변수
배지EC라는 명칭이 실제로는 토양센서일 가능성도 있음
-> 이 경우 EL이 핵심 데이터

### 분석가능 방법
Energy와 Environment의 관계 분석
→ 에너지 사용이 온실 내부 환경 조건에 어떠한 영향을 미치는지 분석한다.
Environment와 Growth의 관계 분석
→ 내부 환경 요인이 작물의 생육 지표에 미치는 영향을 분석한다.
Growth와 Production의 관계 분석
→ 생육 지표가 실제 수확량 및 상품 등급에 어떻게 연결되는지 분석한다.

위의 분석을 통해 설명가능한 조합
1. 특정 환경 조건(온도, 습도, CO₂ 등)을 유지하기 위해 어느 정도의 에너지가 필요한가?
→ 에너지 대비 환경 제어 효율 분석
2. 식물의 성장을 촉진하는 핵심 환경 요인은 무엇인가?
→ 생육에 유의미한 환경 변수 도출
3. 상품의 품질 및 생산량은 어떤 생육 지표와 밀접한 관련이 있는가?
→ 생육 지표와 수확량/등급 간의 구조적 관계 분석
4. 특정 생육 수준을 달성하기 위해 필요한 에너지 투입 수준은 얼마인가?
→ 에너지 → 환경 → 생육 → 생산의 연쇄적 영향 분석
5. 동일한 생산량을 달성하는 데 있어 에너지 사용 효율이 높은 운영 패턴은 무엇인가?
→ Yield 대비 Energy 사용량 분석을 통한 효율적 운영 전략 도출
6. 환경 변동성(예: 온도 변동 폭)이 생육 및 생산 안정성에 미치는 영향은 무엇인가?
→ 평균값이 아닌 ‘환경 안정성’의 중요성 검증 -> std
7. 에너지 투입에는 수확량 증가에 대한 한계가 존재하는가?
→ 과도한 에너지 사용의 비효율성 검증

### 생산정보.cvs 확인

In [4]:
df_production.info()

<class 'pandas.DataFrame'>
RangeIndex: 264 entries, 0 to 263
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   measDate   264 non-null    str
 1   farm_cde   264 non-null    str
 2   itemGrade  264 non-null    str
 3   outtrn     207 non-null    float64
dtypes: float64(1), str(3)
memory usage: 8.4 KB

In [5]:
df_production.head()

     measDate farm_cde itemGrade  outtrn
0  2022-11-16     천지인술       1등급     NaN
1  2022-11-18     천지인술       1등급     NaN
2  2022-11-21     천지인술       1등급     NaN
3  2022-11-23     천지인술       1등급     NaN
4  2022-11-25     천지인술       1등급     NaN

In [6]:
df_production["itemGrade"].value_counts()

itemGrade
1등급      44
2등급      44
3등급      44
4등급      44
비상품과     44
배꼽썩음과    44
Name: count, dtype: int64

In [7]:
df_production["outtrn"].describe()

count    207.000000
mean       2.645488
std        2.915931
min        0.000000
25%        0.685000
50%        1.880000
75%        3.480000
max       23.260000
Name: outtrn, dtype: float64

In [8]:
df_production = df_production.rename(columns={
    "measDate": "measurement_date",
    "farm_cde": "greenhouse_id",
    "itemGrade": "product_grade",
    "outtrn": "harvest_weight_kg"
})

### 생육정보.cvs 확인

In [9]:
df_growth.info()

<class 'pandas.DataFrame'>
RangeIndex: 48 entries, 0 to 47
Data columns (total 13 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   measDate    48 non-null     str
 1   farm_cde    48 non-null     str
 2   itemCode    47 non-null     float64
 3   flowerTop   45 non-null     float64
 4   grwtLt      47 non-null     float64
 5   lefCunt     44 non-null     float64
 6   lefLt       44 non-null     float64
 7   lefBt       45 non-null     float64
 8   stemThck    47 non-null     float64
 9   flanGrupp   44 non-null     float64
 10  frtstGrupp  44 non-null     float64
 11  hvstGrupp   44 non-null     float64
 12  frtstCo     33 non-null     float64
dtypes: float64(11), str(2)
memory usage: 5.0 KB

In [10]:
df_growth.head()

,measDate,farm_cde,itemCode,flowerTop,grwtLt,lefCunt,lefLt,lefBt,stemThck,flanGrupp,frtstGrupp,hvstGrupp,frtstCo
0,2022-09-26,천지인술,80300.0,NaN,20.00,NaN,NaN,NaN,8.539,NaN,NaN,NaN,NaN
1,2022-10-04,천지인술,80300.0,21.92,28.32,8.5,38.35,26.33,9.600,0.54,0.02,0.0,0.1
2,2022-10-10,천지인술,80300.0,24.51,21.71,10.5,40.18,29.04,9.992,1.32,0.82,0.0,4.3
3,2022-10-17,천지인술,80300.0,20.02,26.40,13.2,42.72,38.45,12.529,2.28,1.72,0.0,7.1
4,2022-10-24,천지인술,80300.0,33.93,26.17,13.9,45.76,43.02,10.842,2.96,2.46,0.0,9.5

In [11]:
df_growth = df_growth.rename(columns={
    "measDate": "measurement_date",
    "farm_cde": "greenhouse_id",
    "itemCode": "crop_code",
    "flowerTop": "flower_cluster_height_cm",
    "grwtLt": "growth_length_cm",
    "lefCunt": "leaf_count",
    "lefLt": "leaf_length_cm",
    "lefBt": "leaf_width_cm",
    "stemThck": "stem_diameter_mm",
    "flanGrupp": "flowering_score",
    "frtstGrupp": "fruit_set_score",
    "hvstGrupp": "harvest_stage_score",
    "frtstCo": "fruit_count"
})

### 에너지사용정보.cvs 확인

In [12]:
df_energy.info()

<class 'pandas.DataFrame'>
RangeIndex: 280 entries, 0 to 279
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   measDate              280 non-null    str
 1   farm_cde              280 non-null    str
 2   water_usage           280 non-null    int64
 3   water_cost            280 non-null    int64
 4   fertilizer_usage      280 non-null    int64
 5   fertilizer_cost       280 non-null    int64
 6   heating_energy_usage  280 non-null    int64
 7   heating_energy_cost   280 non-null    int64
 8   CO2_usage             280 non-null    int64
 9   CO2_cost              280 non-null    int64
 10  mist_usage_time       280 non-null    int64
 11  mist_cost             280 non-null    int64
dtypes: int64(10), str(2)
memory usage: 26.4 KB

In [13]:
df_energy.head()

,measDate,farm_cde,water_usage,water_cost,fertilizer_usage,fertilizer_cost,heating_energy_usage,heating_energy_cost,CO2_usage,CO2_cost,mist_usage_time,mist_cost
0,2022-10-01,천지인술,1200,180,3632,4576,0,0,0,0,186,2172
1,2022-10-02,천지인술,90,13,288,362,0,0,0,0,0,0
2,2022-10-03,천지인술,440,66,1452,1829,0,0,0,0,0,0
3,2022-10-04,천지인술,600,90,1802,2270,0,0,0,0,0,0
4,2022-10-05,천지인술,1020,153,3064,3860,18620,1024,0,0,102,1191

In [14]:
df_energy = df_energy.rename(columns={
    "measDate": "measurement_date",
    "farm_cde": "greenhouse_id",
    "water_usage": "water_usage_liters",
    "water_cost": "water_cost_krw",
    "fertilizer_usage": "fertilizer_usage_liters",
    "fertilizer_cost": "fertilizer_cost_krw",
    "heating_energy_usage": "heating_energy_kcal",
    "heating_energy_cost": "heating_energy_cost_krw",
    "CO2_usage": "co2_usage_liters",
    "CO2_cost": "co2_cost_krw",
    "mist_usage_time": "mist_usage_minutes",
    "mist_cost": "mist_cost_krw"
})

### 환경정보.cvs 확인

In [15]:
df_environment.info(show_counts=True)

<class 'pandas.DataFrame'>
RangeIndex: 30867570 entries, 0 to 30867569
Data columns (total 8 columns):
 #   Column      Non-Null Count     Dtype
---  ------      --------------     -----
 0   Unnamed: 0  30867570 non-null  int64
 1   farm_cde    30867570 non-null  str
 2   measDate    30867570 non-null  str
 3   itemCode    30867570 non-null  int64
 4   sectCode    30867570 non-null  str
 5   classCode   30867570 non-null  str
 6   fatrCode    30867570 non-null  str
 7   senVal      30866690 non-null  str
dtypes: int64(2), str(6)
memory usage: 1.8 GB

In [16]:
df_environment.head()

,Unnamed: 0,farm_cde,measDate,itemCode,sectCode,classCode,fatrCode,senVal
0,0,천지인술,2022-09-03 14:42:48,80300,CR,FG,CC24,0
1,1,천지인술,2022-09-03 14:42:48,80300,CR,FG,CC4,0
2,2,천지인술,2022-09-03 14:42:48,80300,CR,FG,CC5,100
3,3,천지인술,2022-09-03 14:42:48,80300,CR,FG,CC6,100
4,4,천지인술,2022-09-03 14:42:48,80300,CR,FG,CC7,100

In [ ]:
df_environment = df_environment.rename(columns={
    "farm_cde": "greenhouse_id",
    "measDate": "measurement_datetime",
    "itemCode": "crop_code",
    "sectCode": "section_code",
    "classCode": "field_code",
    "fatrCode": "sensor_code",
    "senVal": "sensor_value"
})
# Unnamed: Just index column
# field_code: same for all data
df_environment = df_environment.drop(columns=["Unnamed: 0","field_code"])

In [19]:
df_environment["measurement_datetime"] = pd.to_datetime(df_environment["measurement_datetime"])
df_environment["measurement_datetime"] = df_environment["measurement_datetime"].dt.date
df_environment["measurement_datetime"].head()

0    2022-09-03
1    2022-09-03
2    2022-09-03
3    2022-09-03
4    2022-09-03
Name: measurement_datetime, dtype: object